package dev.yukiho.homment.db.model;

import java.util.Date;

public class Cheer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cheer.id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cheer.user_id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cheer.room_id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cheer.created_at
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cheer.comment
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cheer.id
     *
     * @return the value of cheer.id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cheer.id
     *
     * @param id the value for cheer.id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cheer.user_id
     *
     * @return the value of cheer.user_id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cheer.user_id
     *
     * @param userId the value for cheer.user_id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cheer.room_id
     *
     * @return the value of cheer.room_id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cheer.room_id
     *
     * @param roomId the value for cheer.room_id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cheer.created_at
     *
     * @return the value of cheer.created_at
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cheer.created_at
     *
     * @param createdAt the value for cheer.created_at
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cheer.comment
     *
     * @return the value of cheer.comment
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cheer.comment
     *
     * @param comment the value for cheer.comment
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}