package dev.yukiho.homment.db.model;

public class RoomPasswordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_password.id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_password.is_deleted
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_password.id
     *
     * @return the value of room_password.id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_password.id
     *
     * @param id the value for room_password.id
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_password.is_deleted
     *
     * @return the value of room_password.is_deleted
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_password.is_deleted
     *
     * @param isDeleted the value for room_password.is_deleted
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}