package dev.yukiho.homment.db.model;

import java.util.Date;

public class RoomPassword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_password.id
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_password.password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    private Integer password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_password.room_id
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_password.is_deleted
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_password.created_at
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_password.id
     *
     * @return the value of room_password.id
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_password.id
     *
     * @param id the value for room_password.id
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_password.password
     *
     * @return the value of room_password.password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public Integer getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_password.password
     *
     * @param password the value for room_password.password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public void setPassword(Integer password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_password.room_id
     *
     * @return the value of room_password.room_id
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_password.room_id
     *
     * @param roomId the value for room_password.room_id
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_password.is_deleted
     *
     * @return the value of room_password.is_deleted
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_password.is_deleted
     *
     * @param isDeleted the value for room_password.is_deleted
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_password.created_at
     *
     * @return the value of room_password.created_at
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_password.created_at
     *
     * @param createdAt the value for room_password.created_at
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}