package dev.yukiho.homment.db.mapper;

import dev.yukiho.homment.db.model.Cheer;
import dev.yukiho.homment.db.model.CheerExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CheerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    long countByExample(CheerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int deleteByExample(CheerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int insert(Cheer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int insertSelective(Cheer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    List<Cheer> selectByExampleWithBLOBs(CheerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    List<Cheer> selectByExample(CheerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    Cheer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int updateByExampleSelective(@Param("record") Cheer record, @Param("example") CheerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Cheer record, @Param("example") CheerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int updateByExample(@Param("record") Cheer record, @Param("example") CheerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int updateByPrimaryKeySelective(Cheer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Cheer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cheer
     *
     * @mbg.generated Wed Oct 21 05:35:11 JST 2020
     */
    int updateByPrimaryKey(Cheer record);
}