package dev.yukiho.homment.db.mapper;

import dev.yukiho.homment.db.model.RoomPassword;
import dev.yukiho.homment.db.model.RoomPasswordExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoomPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    long countByExample(RoomPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    int deleteByExample(RoomPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    int insert(RoomPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    int insertSelective(RoomPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    List<RoomPassword> selectByExample(RoomPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    RoomPassword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    int updateByExampleSelective(@Param("record") RoomPassword record, @Param("example") RoomPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    int updateByExample(@Param("record") RoomPassword record, @Param("example") RoomPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    int updateByPrimaryKeySelective(RoomPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_password
     *
     * @mbg.generated Sat Oct 24 03:02:10 JST 2020
     */
    int updateByPrimaryKey(RoomPassword record);
}